name: Control Push
on: push

jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest >> log_pytest.txt

      - name: Run flake8 and save results
        run: |
          flake8 . >> log_pytest.txt

      - name: Push logs to repository
        run: |
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git add log_pytest.txt
          git commit -m "Add test and flake8 logs"
          git push

